### PR TITLE
Add the ability to choose the filename

### PR DESCRIPTION
**Pull request by ursi**

### CODE REVIEW

**Comment by bdukes** [comment]
I appreciate the contribution, thanks!  Have you looked at using the [gulp-rename](https://www.npmjs.com/package/gulp-rename) plugin?

**Comment by ursi** [comment]
So if I want my file to be called `elm.js` instead of `Main.js`, are you suggesting I watch `dist/../Main.js` and use `gulp-rename` to change that to `dist/.../elm.js`?

**Comment by bdukes** [comment]
Yes, though I would typically rename it after compiling, something like this:

```js
gulp.src('src/**/Main.elm')
    .pipe(elm())
    .pipe(rename({ basename: 'elm' }))
    .pipe(gulp.dest('dist/'))
```

Let me know if that works for you or if you're looking for something different.

**Comment by ursi** [comment]
ooooh, yeah that makes sense. Thanks!

**Pull request closed without merging**
